# Generated by Django 4.0.5 on 2022-06-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='average',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
